<template>
  <div>
    <h1>{{card.title}}</h1>
    <p>{{ card.description}}</p>
     <div class="loading" v-if="isLoading">
        <img src="../assets/meatwad.gif" />  <!-- progress indicator  -->
     </div>
    <!-- use CommentsList.vue and pass it a value for it's props callef comments --> 
    <comments-list v-bind:comments="card.comments" v-else />
    <div class="board-actions" v-if="!isLoading">
      <router-link
        v-bind:to="{ name: 'Board', params: { id: $route.params.boardID } }"
        >Back to Board</router-link
      >
    </div>
  </div>
</template>

<script>
import CommentsList        from '../components/CommentsList' // Access CommentsList.vue code
import ServiceMcServeServe from '../services/BoardService'   // Access the BoardsServices code 


export default {
  name: "card-detail",
  components: {
    CommentsList
  },
  data() {
    return {
      // property of an individual card - values will come form API call
      card: {
        title: '',
        description: '',
        status: '',
        comments: []
      },
      isLoading: true
    }
  },
      // load the data from the API before the page is generated by Vue
      created() {
        // call the getCard() service to get the clicked cards from API
        //      usingthe BoardID and cardID from the path
        ServiceMcServeServe.getCard(this.$route.params.boardID,
                                    this.$route.params.cardID)
                           // wait for the API call to get done
                           .then(response => {
                             this.card = response  // set the card property to repsonse data
                             this.isLoading = false
                           })
      }
      }
</script>
